header
Yuyakichi/My-Profile1 pull request #1
Opened 2022-02-11 13:18 UTC by Yuyakichi

facebookはやっていないのでリンク先は＃で対応しています。

リストはこれからやろうと思っていますがどのようにするべきなのか考え中です。
案があればお願いします。

確認を宜しくお願い致します。

2022-02-11 13:39 UTC, seiyakanaoka reviewed
デザイン的にはいい感じ👌
ただ、レスポンスがおかしいかな。大きいディスプレイではheader-listがアイコンやタイトルより上にあるのに、サイズが下がると下に移動するから、検証ツールでしっかり見て一定、もしくは意味のある可変をした方がいいな。
あと、小さくなりすぎるとリストが消えてるから、そこは注意してみよう。

2022-02-11 13:39 UTC, seiyakanaoka commented on index.html
> +  <meta http-equiv="X-UA-Compatible" content="IE=edge">
これを入れた意図を教えて欲しい！
いるかな？？

2022-02-11 13:39 UTC, seiyakanaoka commented on index.html
> +    <div class="header-logo">SORA Memory's</div>
構成的には
・font-right
・font-left
にして、どっちかに`header-logo`を入れたいなぁ。それで管理すれば、直感的にもわかりやすいと思う

2022-02-11 13:39 UTC, seiyakanaoka commented on index.html
> +    <div class="header-list">
`header-center`みたいなタグにして、その中に`header-list`を追加、header構成を三つで管理してみよう

2022-02-11 13:39 UTC, seiyakanaoka commented on style.css
> +  height: 300px;
なるべく静的値はしたくないから、paddingで自然な感じにしてみよう

2022-02-11 13:39 UTC, seiyakanaoka commented on style.css
> +  width: 100%;
こういうのは良いと思う👍

2022-02-11 13:39 UTC, seiyakanaoka commented on style.css
> +  padding: 100px 0 150px 300px;
ちょっと大きすぎかな。
display: felxらへんで、管理できないかな？

2022-02-11 13:39 UTC, seiyakanaoka commented on style.css
> +  padding-right: 300px;
これも大きすぎかな。

2022-02-11 13:40 UTC, seiyakanaoka requested changes
デザイン的にはいい感じ👌
ただ、レスポンスがおかしいかな。大きいディスプレイではheader-listがアイコンやタイトルより上にあるのに、サイズが下がると下に移動するから、検証ツールでしっかり見て一定、もしくは意味のある可変をした方がいいな。
あと、小さくなりすぎるとリストが消えてるから、そこは注意してみよう。

2022-02-11 13:40 UTC, seiyakanaoka commented
ごめんコメント二つになったけど、気にせずに。

2022-02-11 13:45 UTC, Yuyakichi commented on index.html
> +  <meta http-equiv="X-UA-Compatible" content="IE=edge">
これはサイトのやつ引っ張ってきてついてたので意味もわからずです。
削除しておきます。

2022-02-11 16:12 UTC, Yuyakichi commented
起きたらみてください。

2022-02-12 01:27 UTC, seiyakanaoka approved these changes
軽微な修正なのでLGTMしておきます。
修正したらマージしてください。

あと、PRの名前は「headerの実装」的な感じで直感的にわかりやすいように書いて欲しい
![LGTM](https://user-images.githubusercontent.com/78468016/153690728-99548160-c7ca-4f13-b9c6-df4ad29cda90.png)

2022-02-12 01:27 UTC, seiyakanaoka commented on about.html
> +<html lang="en">
忘れてた。ここ`lang="ja"`やな。
`en = english`
`ja = japanise`

2022-02-12 01:27 UTC, seiyakanaoka commented on index.html
> +<html lang="en">
ここも

2022-02-12 01:27 UTC, seiyakanaoka commented on style.css
> +@media (max-width: 425px) {
ここまで来たら、ここもコメントアウト書こう

2022-02-17 13:28 UTC, merged