メイン画像作成
Yuyakichi/My-Profile1 pull request #2
Opened 2022-02-12 08:31 UTC by Yuyakichi

レスポンシブも対応済みです。
スマートフォン用は縦書きにしてみました。

確認宜しくお願いします。

2022-02-12 12:22 UTC, seiyakanaoka requested changes
@Yuyakichi 
確認お願いします。

2022-02-12 12:22 UTC, seiyakanaoka commented on about.html
> +<html lang="en">
まだenになってるね

2022-02-12 12:22 UTC, seiyakanaoka commented on about.html
> +<html lang="en">
このhtmlいらんかったら、消してもいいと思う

2022-02-12 12:22 UTC, seiyakanaoka commented on index.html
> +    <img src="file:///Users/igarashiyuya/Downloads/iOS%20%E3%81%AE%E7%94%BB%E5%83%8F.jpg">
この書き方だと、自分（ゆうや）のChromeしか映らんなぁ。
このディレクトリに画像ファイルを入れて、そっからパスを指定しよう

2022-02-12 12:22 UTC, seiyakanaoka commented on index.html
> +    <p>私、五十嵐　蒼空の<br>１年間の思い出の数々を<br>是非ご覧ください！</p>
425pxで崩れてるからもう一度確認お願いします！

2022-02-12 12:22 UTC, seiyakanaoka commented on index.html
> +    <img src="file:///Users/igarashiyuya/Downloads/iOS%20%E3%81%AE%E7%94%BB%E5%83%8F.jpg">
あと、imgはdivで囲って、そこから高さを指定しよう

2022-02-12 12:22 UTC, seiyakanaoka commented on style.css
> +img {
この指定方法はよろしくないかな。ちゃんとクラス指定しよう！

2022-02-12 12:22 UTC, seiyakanaoka commented on style.css
> +.main-image p {
pにもクラス名をつけて、そこから指定してあげよう。
差別化を図ろう

2022-02-12 12:22 UTC, seiyakanaoka commented on style.css
> +  .main-image p {
ここもやね

2022-02-12 12:22 UTC, seiyakanaoka commented on style.css
> +  .main-image p {
ここも

2022-02-12 12:22 UTC, seiyakanaoka commented on style.css
> +  .main-image p {
ここも

2022-02-12 12:22 UTC, seiyakanaoka commented on style.css
> +  .header-list li {
ここも合わせて変えよう

2022-02-12 12:22 UTC, seiyakanaoka commented on style.css
> +  .main-image p {
ここも

2022-02-12 12:22 UTC, seiyakanaoka commented on style.css
> +  .fa {
ここも別クラス名（IDでもいい）を当てよう

2022-02-17 13:42 UTC, seiyakanaoka commented
・.header-list li　みたいな書き方をやめる（明示的にクラスを指定）
・メディアクエリは「iPhone・iPad 縦横と、PC、ディスプレイ」

2022-02-21 13:31 UTC, seiyakanaoka requested changes
全体的にfont-sizeやpaddingが大きすぎます。画像も大きすぎてかなり見づらい状態なので、
もうちょっと全体のレイアウト感や、デザインを意識して実装してみてください。

自分なりにサイトを調べて、検証ツールなどでcssの指定や構成がどうなっているのかを自身で調べてみてください。

ここでもう一段階調べる力、デザイン・構成観点をレベルアップさせましょう（PHPなどで動的Webサイトを作り始めたり、JS実装することを考慮すると、今後かなりコケる気がします。）

ちなみにPHP（などのプログラミング言語）の学習が必要そうなのは、Projectの保守案件やプログラミングスクール講師などの案件では動的サイト・アプリ等を作成し、ドキュメント化したもの（いわゆるポートフォリオ）を提出し、自分の力量がどれくらいあるのか定量化する必要があるためです。
（ぶっちゃけHTML, CSS, JSだけだと差別化測りにくいし（極めるってなったらかなり違いますが、、、）、基本普通のプログラマーなら誰でも触れるっていう認識だけは持っておいた方がいいです。動的サイト触れるようになれば観点とか技術力とか、幅が広がります）

ただ、現職と家庭の両立もあるので、勉強に関してはそこまで焦らなくてもいいと思いますのでご安心を。（勉強のために自分がいるので👍）

手が空いたら自分もPHPとかは勉強しとくんで、PHP始めるってなったら難ありと質問ください（最初はProgateでもいいかな）

2022-02-21 13:31 UTC, seiyakanaoka commented on index.html
>      <img class="image-item" src="./images/main-image.jpg">
```
<div class="main-image">
    <div class="image-mask">
      <p class="image-text">私、五十嵐 蒼空の1年間の思い出の数々を</p>
      <p class="image-text">是非ご覧ください!</p>
      <div class="image-maker-detail">
        <p class="image-text-by">by</p>
        <p class="image-text-name">Yuya Igarashi</p>
      </div>
    </div>
  </div>
```
image-fieldを作ってその中で画像とマスク・文言を作成する

2022-02-21 13:31 UTC, seiyakanaoka commented on style.css
> +  font-size: 70px;
デカすぎやな。
そもそもここでは指定しないで欲しいかな。
header要素全てに対して当たってしまうので。

2022-02-21 13:31 UTC, seiyakanaoka commented on style.css
>    text-align: center;
ここでfont-familyを指定しよう。
フォントの種類はhtmlでImportしてください（種類自分好みのやつをお願いします）。

2022-02-21 13:31 UTC, seiyakanaoka commented on style.css
>    text-align: center;
あとここで`font-size`指定お願いします。
`padding-left`を指定すると余白ができて見栄えが上がります。

2022-02-21 13:31 UTC, seiyakanaoka commented on index.html
`<head></head>`内でfont-familyの指定をお願いします。

2022-02-21 13:31 UTC, seiyakanaoka commented on style.css
>  .header-left {
下ですが、ここのimport はhtml内でやりましょう。

2022-02-21 13:31 UTC, seiyakanaoka commented on style.css
>  .header-left {
paddingがデカすぎるのと、leftで指定しなくてもいいと思う。
paddingの指定方法についてもうちょっと調べてみてください。

2022-02-21 13:31 UTC, seiyakanaoka commented on style.css
> +  font-size: 40px;
デカすぎますね。28pxくらいはどうかい？

2022-02-21 13:31 UTC, seiyakanaoka commented on style.css
> +  font-size: 25px;
大きいのと、奇数ではあまり指定したくないかな。（後々管理しづらい）
4の倍数だと色々都合いいです。

2022-02-21 13:31 UTC, seiyakanaoka commented on style.css
以下のコードを追加ください。
そして理解の落とし込みお願いします。

```
.main-image {
  position: relative;
  width: 100%; /* 横幅いっぱい */
  height: 500px; /* 高さ300px */
  background-image: url(./images/main-image.jpg);
  background-size: cover; /* 縦横比を維持したまま背景領域を埋め尽くす */
  background-position: center; /* 背景画像を中央に配置 */
}

.image-mask {
  display: flex;
  /* align-items: center; */
  justify-content: center;
  flex-direction: column;
  padding-left: 56px;
  gap: 12px;
  width: 45%;
  height: 100%;
  background-color: rgb(0 0 0 / 50%);
}

.image-text {
  color: #fff;
  border-radius: 30px;
  top: 40%;
  right: 60%;
  font-size: 24px;
  font-family: "Sawarabi Mincho";
}

.image-maker-detail {
  display: flex;
  align-items: center;
  top: 200;
  gap: 8px;
  color: #fff;
  font-family: "Sawarabi Mincho";
}

.image-text-by {
  font-size: 16px;
}

.image-text-name {
  font-size: 20px;
}
```

2022-02-21 13:31 UTC, seiyakanaoka commented on style.css
font-familyのところは自由です。
[Google-font](https://googlefonts.github.io/japanese/#sawarabimincho)なりで探して自分好みにしてください。

2022-02-21 13:31 UTC, seiyakanaoka commented on style.css
画像の大きさやスタイルはメディアクエリお願いします。

2022-02-25 23:31 UTC, seiyakanaoka requested changes
@Yuyakichi 
軽微です。確認願います。

2022-02-25 23:31 UTC, seiyakanaoka commented on style.css
> +  margin: 24% 0;
ちなみに、ヘッダーサイズはこの幅が好みって感じかな？？
であれば、ヘッダーの幅をどこかで決めたいので、このマージンでは決めたくないなぁ。
header要素にpadding指定したりでいけないですかね。

2022-02-25 23:31 UTC, seiyakanaoka commented on style.css
> +  font-family: "Nico Moji";
なんか漢字だけ、フォントスタイル当たってなくないですかね？？

2022-02-27 06:17 UTC, seiyakanaoka commented
![LGTM](https://user-images.githubusercontent.com/78468016/155870781-35515197-fe18-457b-8414-f96370952a54.png)

2022-02-27 06:23 UTC, Yuyakichi commented on style.css
> +  font-size: 70px;
1440px での見た目を変更しました。

2022-02-27 06:23 UTC, Yuyakichi commented on style.css
> +  background-color: white;
色合い的に変えて見ました。

2022-02-27 06:23 UTC, Yuyakichi commented on style.css
>  }
メディアクエリはおそらく全サイズ適応しております。

2022-02-27 06:23 UTC, Yuyakichi commented on style.css
> +
HTMLでlinkでやるのとCSSでimportはどちらでも問題ないのでしょうか？？
ここの部分はサイトにlinkがなかったためimportで対応しています。

2022-02-27 06:23 UTC, Yuyakichi commented on index.html
> +
ここスペースいらないですね！すみません。
段落で扱いたかったため<br>でまとめ対応しました。

2022-02-27 06:23 UTC, Yuyakichi commented on style.css
> +  font-size: 28px;
ここにfont-familyを追加との事でしたが、linkから引っ張ってきてるアイコンでも変更はかけれるのですか？？
わからなかったので追加していません。

2022-02-27 06:23 UTC, Yuyakichi commented on style.css
> +  align-items: center;
ここコメントになってて、ん？ってなりましたwww
直しています！

2022-02-27 06:23 UTC, Yuyakichi commented on style.css
>    border-radius: 30px;
ここいらないかもですね！？

2022-02-27 06:23 UTC, Yuyakichi commented on style.css
> +  background-color: rgb(0 0 0 / 50%);
ここの50%というのは、明度ですよね？？
つける理由を知りたいです。100%だと問題ありなのですか？

2022-02-27 06:23 UTC, Yuyakichi commented on style.css
>    writing-mode: vertical-rl;
画面サイズ768で縦書きにしたのですが、横の方がいいですか？
後、縦書きにすると、1や!が横になってしまいます。これはfont-familyのせいでしょうか？

2022-02-27 06:23 UTC, Yuyakichi commented on style.css
> +
paddingなので%を沢山使っていますがpxの方が良いとかはあるのでしょうか？

flex-boxの使い方やここに書いたプロパティーの使い方は理解できました。家にある本で見ながらもありますが。
PHPも隙間時間に触って起きます！

レビュー、質問回答（長くなりそうや、文字で難しければできるときの電話でも大丈夫です）宜しくお願いします！

2022-02-27 06:24 UTC, Yuyakichi commented on index.html
>    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.3.0/css/font-awesome.min.css">
あああ

2022-02-27 06:26 UTC, merged